### ISSUE TITLE
Upgrade to 5.0.1 ?

### ISSUE THREAD

**Issue by ringe** [abtris/nginx-passenger#3]
https://blog.phusion.nl/2015/03/04/phusion-passenger-5-0-1-released/

**Comment by nickhammond** [comment]
The apt repository that this playbook uses is the main Phusion repository which now contains version 5(5.0.7 as of now). You have to explicitly add the Passenger 4 repository if you want version 4. To upgrade you would just run an ad-hoc command to update the apt cache and with a state of latest for nginx-extras & passenger.

**Comment by ringe** [comment]
Thanks
